---
- name: Deploy simple Shiny app
  hosts: shiny_hosts
  become: true

  vars:
    repo_url: "https://github.com/SimpleVM/simplevm-services-demo-shiny.git"
    repo_dest: "/home/{{ ansible_user }}/shiny-demo"
    repo_version: "main"
    app_port: 3838
    app_base_url: "shiny_100" #adjust to subpath

  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: true

    - name: Install R and Shiny
      ansible.builtin.apt:
        name:
          - r-base
          - r-cran-shiny
        state: present

    - name: Pull repository into home directory
      become: false
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ repo_version }}"
        update: true
        force: true

    - name: Create systemd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/shiny-app.service
        content: |
          [Unit]
          Description=Shiny Application Service
          After=network.target

          [Service]
          Type=simple
          User={{ ansible_user }}
          WorkingDirectory={{ repo_dest }}
          Environment="SHINY_BASE_PATH={{ app_base_url }}"
          ExecStart=/usr/bin/Rscript -e "shiny::runApp(appDir='{{ repo_dest }}/app', host='0.0.0.0', port={{ app_port }})"
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable Shiny app service to start on boot
      ansible.builtin.systemd:
        name: shiny-app
        enabled: true

    - name: Start and restart Shiny app service
      ansible.builtin.systemd:
        name: shiny-app
        state: restarted
