---
- name: Deploy simple Shiny app
  hosts: shiny_hosts
  become: true

  vars:
    repo_url: "https://github.com/SimpleVM/simplevm-services-demo-shiny.git"
    repo_dest: "/srv/shiny-server/shiny_100_repo"
    repo_version: "main"
    app_port: 3838
    app_base_url: "/shiny_100" #adjust to subpath
    shiny_server_deb_url: "https://download3.rstudio.org/ubuntu-20.04/x86_64/shiny-server-1.5.23.1030-amd64.deb"
    shiny_server_deb_path: "/tmp/shiny-server.deb"

  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: true

    - name: Install R and Shiny
      ansible.builtin.apt:
        name:
          - r-base
          - r-cran-shiny
        state: present

    - name: Pull repository into service directory
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ repo_version }}"
        update: true
        force: true

    - name: Install gdebi-core
      ansible.builtin.apt:
        name: gdebi-core
        state: present

    - name: Download Shiny Server
      ansible.builtin.get_url:
        url: "{{ shiny_server_deb_url }}"
        dest: "{{ shiny_server_deb_path }}"

    - name: Install Shiny Server
      ansible.builtin.shell: "gdebi -n {{ shiny_server_deb_path }}"
      args:
        creates: /usr/bin/shiny-server

    - name: Create symbolic link for Shiny app
      ansible.builtin.file:
        src: "{{ repo_dest }}/app"
        dest: "/srv/shiny-server{{ app_base_url }}"
        state: link

    - name: Ensure Shiny Server is started and enabled
      ansible.builtin.systemd:
        name: shiny-server
        state: started
        enabled: true

    - name: Fix ownership for shiny user
      ansible.builtin.file:
        path: /srv/shiny-server
        owner: shiny
        group: shiny
        recurse: true
